/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRepairInsightsTestRouteImport } from './routes/_authenticated/repair-insights-test'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedErrorCodesRouteImport } from './routes/_authenticated/error-codes'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDiagnoseRouteImport } from './routes/_authenticated/diagnose'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedHistoryIdRouteImport } from './routes/_authenticated/history.$id'
import { Route as AuthenticatedCommunitySearchRouteImport } from './routes/_authenticated/community.search'
import { Route as AuthenticatedCommunityNewRouteImport } from './routes/_authenticated/community.new'
import { Route as AuthenticatedCommunityBrowseRouteImport } from './routes/_authenticated/community.browse'
import { Route as AuthenticatedCommunityDiscussionIdRouteImport } from './routes/_authenticated/community.$discussionId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRepairInsightsTestRoute =
  AuthenticatedRepairInsightsTestRouteImport.update({
    id: '/repair-insights-test',
    path: '/repair-insights-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorCodesRoute = AuthenticatedErrorCodesRouteImport.update({
  id: '/error-codes',
  path: '/error-codes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnoseRoute = AuthenticatedDiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedHistoryIdRoute = AuthenticatedHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedHistoryRoute,
} as any)
const AuthenticatedCommunitySearchRoute =
  AuthenticatedCommunitySearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityNewRoute =
  AuthenticatedCommunityNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityBrowseRoute =
  AuthenticatedCommunityBrowseRouteImport.update({
    id: '/browse',
    path: '/browse',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityDiscussionIdRoute =
  AuthenticatedCommunityDiscussionIdRouteImport.update({
    id: '/$discussionId',
    path: '/$discussionId',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/beta': typeof BetaRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnose': typeof AuthenticatedDiagnoseRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/error-codes': typeof AuthenticatedErrorCodesRoute
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/owner': typeof AuthenticatedOwnerRoute
  '/repair-insights-test': typeof AuthenticatedRepairInsightsTestRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/community/$discussionId': typeof AuthenticatedCommunityDiscussionIdRoute
  '/community/browse': typeof AuthenticatedCommunityBrowseRoute
  '/community/new': typeof AuthenticatedCommunityNewRoute
  '/community/search': typeof AuthenticatedCommunitySearchRoute
  '/history/$id': typeof AuthenticatedHistoryIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/beta': typeof BetaRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnose': typeof AuthenticatedDiagnoseRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/error-codes': typeof AuthenticatedErrorCodesRoute
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/owner': typeof AuthenticatedOwnerRoute
  '/repair-insights-test': typeof AuthenticatedRepairInsightsTestRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/community/$discussionId': typeof AuthenticatedCommunityDiscussionIdRoute
  '/community/browse': typeof AuthenticatedCommunityBrowseRoute
  '/community/new': typeof AuthenticatedCommunityNewRoute
  '/community/search': typeof AuthenticatedCommunitySearchRoute
  '/history/$id': typeof AuthenticatedHistoryIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/beta': typeof BetaRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnose': typeof AuthenticatedDiagnoseRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/error-codes': typeof AuthenticatedErrorCodesRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRouteWithChildren
  '/_authenticated/owner': typeof AuthenticatedOwnerRoute
  '/_authenticated/repair-insights-test': typeof AuthenticatedRepairInsightsTestRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/community/$discussionId': typeof AuthenticatedCommunityDiscussionIdRoute
  '/_authenticated/community/browse': typeof AuthenticatedCommunityBrowseRoute
  '/_authenticated/community/new': typeof AuthenticatedCommunityNewRoute
  '/_authenticated/community/search': typeof AuthenticatedCommunitySearchRoute
  '/_authenticated/history/$id': typeof AuthenticatedHistoryIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/beta'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/community'
    | '/dashboard'
    | '/diagnose'
    | '/documents'
    | '/error-codes'
    | '/history'
    | '/owner'
    | '/repair-insights-test'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/community/$discussionId'
    | '/community/browse'
    | '/community/new'
    | '/community/search'
    | '/history/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/beta'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/community'
    | '/dashboard'
    | '/diagnose'
    | '/documents'
    | '/error-codes'
    | '/history'
    | '/owner'
    | '/repair-insights-test'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/community/$discussionId'
    | '/community/browse'
    | '/community/new'
    | '/community/search'
    | '/history/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/access-denied'
    | '/auth'
    | '/beta'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnose'
    | '/_authenticated/documents'
    | '/_authenticated/error-codes'
    | '/_authenticated/history'
    | '/_authenticated/owner'
    | '/_authenticated/repair-insights-test'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/community/$discussionId'
    | '/_authenticated/community/browse'
    | '/_authenticated/community/new'
    | '/_authenticated/community/search'
    | '/_authenticated/history/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuthRoute: typeof AuthRoute
  BetaRoute: typeof BetaRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/repair-insights-test': {
      id: '/_authenticated/repair-insights-test'
      path: '/repair-insights-test'
      fullPath: '/repair-insights-test'
      preLoaderRoute: typeof AuthenticatedRepairInsightsTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/error-codes': {
      id: '/_authenticated/error-codes'
      path: '/error-codes'
      fullPath: '/error-codes'
      preLoaderRoute: typeof AuthenticatedErrorCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnose': {
      id: '/_authenticated/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof AuthenticatedDiagnoseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history/$id': {
      id: '/_authenticated/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof AuthenticatedHistoryIdRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
    '/_authenticated/community/search': {
      id: '/_authenticated/community/search'
      path: '/search'
      fullPath: '/community/search'
      preLoaderRoute: typeof AuthenticatedCommunitySearchRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/new': {
      id: '/_authenticated/community/new'
      path: '/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof AuthenticatedCommunityNewRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/browse': {
      id: '/_authenticated/community/browse'
      path: '/browse'
      fullPath: '/community/browse'
      preLoaderRoute: typeof AuthenticatedCommunityBrowseRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/$discussionId': {
      id: '/_authenticated/community/$discussionId'
      path: '/$discussionId'
      fullPath: '/community/$discussionId'
      preLoaderRoute: typeof AuthenticatedCommunityDiscussionIdRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCommunityRouteChildren {
  AuthenticatedCommunityDiscussionIdRoute: typeof AuthenticatedCommunityDiscussionIdRoute
  AuthenticatedCommunityBrowseRoute: typeof AuthenticatedCommunityBrowseRoute
  AuthenticatedCommunityNewRoute: typeof AuthenticatedCommunityNewRoute
  AuthenticatedCommunitySearchRoute: typeof AuthenticatedCommunitySearchRoute
}

const AuthenticatedCommunityRouteChildren: AuthenticatedCommunityRouteChildren =
  {
    AuthenticatedCommunityDiscussionIdRoute:
      AuthenticatedCommunityDiscussionIdRoute,
    AuthenticatedCommunityBrowseRoute: AuthenticatedCommunityBrowseRoute,
    AuthenticatedCommunityNewRoute: AuthenticatedCommunityNewRoute,
    AuthenticatedCommunitySearchRoute: AuthenticatedCommunitySearchRoute,
  }

const AuthenticatedCommunityRouteWithChildren =
  AuthenticatedCommunityRoute._addFileChildren(
    AuthenticatedCommunityRouteChildren,
  )

interface AuthenticatedHistoryRouteChildren {
  AuthenticatedHistoryIdRoute: typeof AuthenticatedHistoryIdRoute
}

const AuthenticatedHistoryRouteChildren: AuthenticatedHistoryRouteChildren = {
  AuthenticatedHistoryIdRoute: AuthenticatedHistoryIdRoute,
}

const AuthenticatedHistoryRouteWithChildren =
  AuthenticatedHistoryRoute._addFileChildren(AuthenticatedHistoryRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnoseRoute: typeof AuthenticatedDiagnoseRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedErrorCodesRoute: typeof AuthenticatedErrorCodesRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRouteWithChildren
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRoute
  AuthenticatedRepairInsightsTestRoute: typeof AuthenticatedRepairInsightsTestRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommunityRoute: AuthenticatedCommunityRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnoseRoute: AuthenticatedDiagnoseRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedErrorCodesRoute: AuthenticatedErrorCodesRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRouteWithChildren,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRoute,
  AuthenticatedRepairInsightsTestRoute: AuthenticatedRepairInsightsTestRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  AuthRoute: AuthRoute,
  BetaRoute: BetaRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
