/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnoseRouteImport } from './routes/_authenticated/diagnose'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedErrorCodesRouteImport } from './routes/_authenticated/error-codes'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedRepairInsightsTestRouteImport } from './routes/_authenticated/repair-insights-test'
import { Route as AuthenticatedTechTalkRouteImport } from './routes/_authenticated/tech-talk'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedCommunityDiscussionIdRouteImport } from './routes/_authenticated/community.$discussionId'
import { Route as AuthenticatedCommunityBrowseRouteImport } from './routes/_authenticated/community.browse'
import { Route as AuthenticatedCommunityConfirmedRepairsRouteImport } from './routes/_authenticated/community.confirmed-repairs'
import { Route as AuthenticatedCommunityNewRouteImport } from './routes/_authenticated/community.new'
import { Route as AuthenticatedCommunitySearchRouteImport } from './routes/_authenticated/community.search'
import { Route as AuthenticatedHistoryIdRouteImport } from './routes/_authenticated/history.$id'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner/index'
import { Route as AuthenticatedOwnerEmailsRouteImport } from './routes/_authenticated/owner/emails'
import { Route as AuthenticatedOwnerKnowledgeRouteImport } from './routes/_authenticated/owner/knowledge'
import { Route as AuthenticatedOwnerPaymentsRouteImport } from './routes/_authenticated/owner/payments'
import { Route as AuthenticatedOwnerToolsRouteImport } from './routes/_authenticated/owner/tools'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedCommunityConfirmedRepairsOutcomeIdRouteImport } from './routes/_authenticated/community.confirmed-repairs.$outcomeId'
import { Route as AuthenticatedOwnerToolsToolIdRouteImport } from './routes/_authenticated/owner/tools.$toolId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnoseRoute = AuthenticatedDiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorCodesRoute = AuthenticatedErrorCodesRouteImport.update({
  id: '/error-codes',
  path: '/error-codes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepairInsightsTestRoute =
  AuthenticatedRepairInsightsTestRouteImport.update({
    id: '/repair-insights-test',
    path: '/repair-insights-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTechTalkRoute = AuthenticatedTechTalkRouteImport.update({
  id: '/tech-talk',
  path: '/tech-talk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCommunityDiscussionIdRoute =
  AuthenticatedCommunityDiscussionIdRouteImport.update({
    id: '/$discussionId',
    path: '/$discussionId',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityBrowseRoute =
  AuthenticatedCommunityBrowseRouteImport.update({
    id: '/browse',
    path: '/browse',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityConfirmedRepairsRoute =
  AuthenticatedCommunityConfirmedRepairsRouteImport.update({
    id: '/confirmed-repairs',
    path: '/confirmed-repairs',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunityNewRoute =
  AuthenticatedCommunityNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedCommunitySearchRoute =
  AuthenticatedCommunitySearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedCommunityRoute,
  } as any)
const AuthenticatedHistoryIdRoute = AuthenticatedHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedHistoryRoute,
} as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedOwnerEmailsRoute =
  AuthenticatedOwnerEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerKnowledgeRoute =
  AuthenticatedOwnerKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerPaymentsRoute =
  AuthenticatedOwnerPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerToolsRoute = AuthenticatedOwnerToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommunityConfirmedRepairsOutcomeIdRoute =
  AuthenticatedCommunityConfirmedRepairsOutcomeIdRouteImport.update({
    id: '/$outcomeId',
    path: '/$outcomeId',
    getParentRoute: () => AuthenticatedCommunityConfirmedRepairsRoute,
  } as any)
const AuthenticatedOwnerToolsToolIdRoute =
  AuthenticatedOwnerToolsToolIdRouteImport.update({
    id: '/$toolId',
    path: '/$toolId',
    getParentRoute: () => AuthenticatedOwnerToolsRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/beta': typeof BetaRoute
  '/mcp': typeof McpRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnose': typeof AuthenticatedDiagnoseRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/error-codes': typeof AuthenticatedErrorCodesRoute
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/repair-insights-test': typeof AuthenticatedRepairInsightsTestRoute
  '/tech-talk': typeof AuthenticatedTechTalkRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/community/$discussionId': typeof AuthenticatedCommunityDiscussionIdRoute
  '/community/browse': typeof AuthenticatedCommunityBrowseRoute
  '/community/confirmed-repairs': typeof AuthenticatedCommunityConfirmedRepairsRouteWithChildren
  '/community/new': typeof AuthenticatedCommunityNewRoute
  '/community/search': typeof AuthenticatedCommunitySearchRoute
  '/history/$id': typeof AuthenticatedHistoryIdRoute
  '/owner/emails': typeof AuthenticatedOwnerEmailsRoute
  '/owner/knowledge': typeof AuthenticatedOwnerKnowledgeRoute
  '/owner/payments': typeof AuthenticatedOwnerPaymentsRoute
  '/owner/tools': typeof AuthenticatedOwnerToolsRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
  '/community/confirmed-repairs/$outcomeId': typeof AuthenticatedCommunityConfirmedRepairsOutcomeIdRoute
  '/owner/tools/$toolId': typeof AuthenticatedOwnerToolsToolIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/beta': typeof BetaRoute
  '/mcp': typeof McpRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/community': typeof AuthenticatedCommunityRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnose': typeof AuthenticatedDiagnoseRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/error-codes': typeof AuthenticatedErrorCodesRoute
  '/history': typeof AuthenticatedHistoryRouteWithChildren
  '/repair-insights-test': typeof AuthenticatedRepairInsightsTestRoute
  '/tech-talk': typeof AuthenticatedTechTalkRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/community/$discussionId': typeof AuthenticatedCommunityDiscussionIdRoute
  '/community/browse': typeof AuthenticatedCommunityBrowseRoute
  '/community/confirmed-repairs': typeof AuthenticatedCommunityConfirmedRepairsRouteWithChildren
  '/community/new': typeof AuthenticatedCommunityNewRoute
  '/community/search': typeof AuthenticatedCommunitySearchRoute
  '/history/$id': typeof AuthenticatedHistoryIdRoute
  '/owner/emails': typeof AuthenticatedOwnerEmailsRoute
  '/owner/knowledge': typeof AuthenticatedOwnerKnowledgeRoute
  '/owner/payments': typeof AuthenticatedOwnerPaymentsRoute
  '/owner/tools': typeof AuthenticatedOwnerToolsRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
  '/community/confirmed-repairs/$outcomeId': typeof AuthenticatedCommunityConfirmedRepairsOutcomeIdRoute
  '/owner/tools/$toolId': typeof AuthenticatedOwnerToolsToolIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/beta': typeof BetaRoute
  '/mcp': typeof McpRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnose': typeof AuthenticatedDiagnoseRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/error-codes': typeof AuthenticatedErrorCodesRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRouteWithChildren
  '/_authenticated/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/_authenticated/repair-insights-test': typeof AuthenticatedRepairInsightsTestRoute
  '/_authenticated/tech-talk': typeof AuthenticatedTechTalkRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/community/$discussionId': typeof AuthenticatedCommunityDiscussionIdRoute
  '/_authenticated/community/browse': typeof AuthenticatedCommunityBrowseRoute
  '/_authenticated/community/confirmed-repairs': typeof AuthenticatedCommunityConfirmedRepairsRouteWithChildren
  '/_authenticated/community/new': typeof AuthenticatedCommunityNewRoute
  '/_authenticated/community/search': typeof AuthenticatedCommunitySearchRoute
  '/_authenticated/history/$id': typeof AuthenticatedHistoryIdRoute
  '/_authenticated/owner/emails': typeof AuthenticatedOwnerEmailsRoute
  '/_authenticated/owner/knowledge': typeof AuthenticatedOwnerKnowledgeRoute
  '/_authenticated/owner/payments': typeof AuthenticatedOwnerPaymentsRoute
  '/_authenticated/owner/tools': typeof AuthenticatedOwnerToolsRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
  '/_authenticated/community/confirmed-repairs/$outcomeId': typeof AuthenticatedCommunityConfirmedRepairsOutcomeIdRoute
  '/_authenticated/owner/tools/$toolId': typeof AuthenticatedOwnerToolsToolIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/beta'
    | '/mcp'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/community'
    | '/dashboard'
    | '/diagnose'
    | '/documents'
    | '/error-codes'
    | '/history'
    | '/owner'
    | '/repair-insights-test'
    | '/tech-talk'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/community/$discussionId'
    | '/community/browse'
    | '/community/confirmed-repairs'
    | '/community/new'
    | '/community/search'
    | '/history/$id'
    | '/owner/emails'
    | '/owner/knowledge'
    | '/owner/payments'
    | '/owner/tools'
    | '/lovable/email/suppression'
    | '/owner/'
    | '/community/confirmed-repairs/$outcomeId'
    | '/owner/tools/$toolId'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/auth'
    | '/beta'
    | '/mcp'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/community'
    | '/dashboard'
    | '/diagnose'
    | '/documents'
    | '/error-codes'
    | '/history'
    | '/repair-insights-test'
    | '/tech-talk'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/community/$discussionId'
    | '/community/browse'
    | '/community/confirmed-repairs'
    | '/community/new'
    | '/community/search'
    | '/history/$id'
    | '/owner/emails'
    | '/owner/knowledge'
    | '/owner/payments'
    | '/owner/tools'
    | '/lovable/email/suppression'
    | '/owner'
    | '/community/confirmed-repairs/$outcomeId'
    | '/owner/tools/$toolId'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/access-denied'
    | '/auth'
    | '/beta'
    | '/mcp'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnose'
    | '/_authenticated/documents'
    | '/_authenticated/error-codes'
    | '/_authenticated/history'
    | '/_authenticated/owner'
    | '/_authenticated/repair-insights-test'
    | '/_authenticated/tech-talk'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/community/$discussionId'
    | '/_authenticated/community/browse'
    | '/_authenticated/community/confirmed-repairs'
    | '/_authenticated/community/new'
    | '/_authenticated/community/search'
    | '/_authenticated/history/$id'
    | '/_authenticated/owner/emails'
    | '/_authenticated/owner/knowledge'
    | '/_authenticated/owner/payments'
    | '/_authenticated/owner/tools'
    | '/lovable/email/suppression'
    | '/_authenticated/owner/'
    | '/_authenticated/community/confirmed-repairs/$outcomeId'
    | '/_authenticated/owner/tools/$toolId'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuthRoute: typeof AuthRoute
  BetaRoute: typeof BetaRoute
  McpRoute: typeof McpRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnose': {
      id: '/_authenticated/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof AuthenticatedDiagnoseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/error-codes': {
      id: '/_authenticated/error-codes'
      path: '/error-codes'
      fullPath: '/error-codes'
      preLoaderRoute: typeof AuthenticatedErrorCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repair-insights-test': {
      id: '/_authenticated/repair-insights-test'
      path: '/repair-insights-test'
      fullPath: '/repair-insights-test'
      preLoaderRoute: typeof AuthenticatedRepairInsightsTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tech-talk': {
      id: '/_authenticated/tech-talk'
      path: '/tech-talk'
      fullPath: '/tech-talk'
      preLoaderRoute: typeof AuthenticatedTechTalkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/community/$discussionId': {
      id: '/_authenticated/community/$discussionId'
      path: '/$discussionId'
      fullPath: '/community/$discussionId'
      preLoaderRoute: typeof AuthenticatedCommunityDiscussionIdRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/browse': {
      id: '/_authenticated/community/browse'
      path: '/browse'
      fullPath: '/community/browse'
      preLoaderRoute: typeof AuthenticatedCommunityBrowseRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/confirmed-repairs': {
      id: '/_authenticated/community/confirmed-repairs'
      path: '/confirmed-repairs'
      fullPath: '/community/confirmed-repairs'
      preLoaderRoute: typeof AuthenticatedCommunityConfirmedRepairsRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/new': {
      id: '/_authenticated/community/new'
      path: '/new'
      fullPath: '/community/new'
      preLoaderRoute: typeof AuthenticatedCommunityNewRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/community/search': {
      id: '/_authenticated/community/search'
      path: '/search'
      fullPath: '/community/search'
      preLoaderRoute: typeof AuthenticatedCommunitySearchRouteImport
      parentRoute: typeof AuthenticatedCommunityRoute
    }
    '/_authenticated/history/$id': {
      id: '/_authenticated/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof AuthenticatedHistoryIdRouteImport
      parentRoute: typeof AuthenticatedHistoryRoute
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/emails': {
      id: '/_authenticated/owner/emails'
      path: '/emails'
      fullPath: '/owner/emails'
      preLoaderRoute: typeof AuthenticatedOwnerEmailsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/knowledge': {
      id: '/_authenticated/owner/knowledge'
      path: '/knowledge'
      fullPath: '/owner/knowledge'
      preLoaderRoute: typeof AuthenticatedOwnerKnowledgeRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/payments': {
      id: '/_authenticated/owner/payments'
      path: '/payments'
      fullPath: '/owner/payments'
      preLoaderRoute: typeof AuthenticatedOwnerPaymentsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/tools': {
      id: '/_authenticated/owner/tools'
      path: '/tools'
      fullPath: '/owner/tools'
      preLoaderRoute: typeof AuthenticatedOwnerToolsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/community/confirmed-repairs/$outcomeId': {
      id: '/_authenticated/community/confirmed-repairs/$outcomeId'
      path: '/$outcomeId'
      fullPath: '/community/confirmed-repairs/$outcomeId'
      preLoaderRoute: typeof AuthenticatedCommunityConfirmedRepairsOutcomeIdRouteImport
      parentRoute: typeof AuthenticatedCommunityConfirmedRepairsRoute
    }
    '/_authenticated/owner/tools/$toolId': {
      id: '/_authenticated/owner/tools/$toolId'
      path: '/$toolId'
      fullPath: '/owner/tools/$toolId'
      preLoaderRoute: typeof AuthenticatedOwnerToolsToolIdRouteImport
      parentRoute: typeof AuthenticatedOwnerToolsRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCommunityConfirmedRepairsRouteChildren {
  AuthenticatedCommunityConfirmedRepairsOutcomeIdRoute: typeof AuthenticatedCommunityConfirmedRepairsOutcomeIdRoute
}

const AuthenticatedCommunityConfirmedRepairsRouteChildren: AuthenticatedCommunityConfirmedRepairsRouteChildren =
  {
    AuthenticatedCommunityConfirmedRepairsOutcomeIdRoute:
      AuthenticatedCommunityConfirmedRepairsOutcomeIdRoute,
  }

const AuthenticatedCommunityConfirmedRepairsRouteWithChildren =
  AuthenticatedCommunityConfirmedRepairsRoute._addFileChildren(
    AuthenticatedCommunityConfirmedRepairsRouteChildren,
  )

interface AuthenticatedCommunityRouteChildren {
  AuthenticatedCommunityDiscussionIdRoute: typeof AuthenticatedCommunityDiscussionIdRoute
  AuthenticatedCommunityBrowseRoute: typeof AuthenticatedCommunityBrowseRoute
  AuthenticatedCommunityConfirmedRepairsRoute: typeof AuthenticatedCommunityConfirmedRepairsRouteWithChildren
  AuthenticatedCommunityNewRoute: typeof AuthenticatedCommunityNewRoute
  AuthenticatedCommunitySearchRoute: typeof AuthenticatedCommunitySearchRoute
}

const AuthenticatedCommunityRouteChildren: AuthenticatedCommunityRouteChildren =
  {
    AuthenticatedCommunityDiscussionIdRoute:
      AuthenticatedCommunityDiscussionIdRoute,
    AuthenticatedCommunityBrowseRoute: AuthenticatedCommunityBrowseRoute,
    AuthenticatedCommunityConfirmedRepairsRoute:
      AuthenticatedCommunityConfirmedRepairsRouteWithChildren,
    AuthenticatedCommunityNewRoute: AuthenticatedCommunityNewRoute,
    AuthenticatedCommunitySearchRoute: AuthenticatedCommunitySearchRoute,
  }

const AuthenticatedCommunityRouteWithChildren =
  AuthenticatedCommunityRoute._addFileChildren(
    AuthenticatedCommunityRouteChildren,
  )

interface AuthenticatedHistoryRouteChildren {
  AuthenticatedHistoryIdRoute: typeof AuthenticatedHistoryIdRoute
}

const AuthenticatedHistoryRouteChildren: AuthenticatedHistoryRouteChildren = {
  AuthenticatedHistoryIdRoute: AuthenticatedHistoryIdRoute,
}

const AuthenticatedHistoryRouteWithChildren =
  AuthenticatedHistoryRoute._addFileChildren(AuthenticatedHistoryRouteChildren)

interface AuthenticatedOwnerToolsRouteChildren {
  AuthenticatedOwnerToolsToolIdRoute: typeof AuthenticatedOwnerToolsToolIdRoute
}

const AuthenticatedOwnerToolsRouteChildren: AuthenticatedOwnerToolsRouteChildren =
  {
    AuthenticatedOwnerToolsToolIdRoute: AuthenticatedOwnerToolsToolIdRoute,
  }

const AuthenticatedOwnerToolsRouteWithChildren =
  AuthenticatedOwnerToolsRoute._addFileChildren(
    AuthenticatedOwnerToolsRouteChildren,
  )

interface AuthenticatedOwnerRouteChildren {
  AuthenticatedOwnerEmailsRoute: typeof AuthenticatedOwnerEmailsRoute
  AuthenticatedOwnerKnowledgeRoute: typeof AuthenticatedOwnerKnowledgeRoute
  AuthenticatedOwnerPaymentsRoute: typeof AuthenticatedOwnerPaymentsRoute
  AuthenticatedOwnerToolsRoute: typeof AuthenticatedOwnerToolsRouteWithChildren
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
}

const AuthenticatedOwnerRouteChildren: AuthenticatedOwnerRouteChildren = {
  AuthenticatedOwnerEmailsRoute: AuthenticatedOwnerEmailsRoute,
  AuthenticatedOwnerKnowledgeRoute: AuthenticatedOwnerKnowledgeRoute,
  AuthenticatedOwnerPaymentsRoute: AuthenticatedOwnerPaymentsRoute,
  AuthenticatedOwnerToolsRoute: AuthenticatedOwnerToolsRouteWithChildren,
  AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
}

const AuthenticatedOwnerRouteWithChildren =
  AuthenticatedOwnerRoute._addFileChildren(AuthenticatedOwnerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnoseRoute: typeof AuthenticatedDiagnoseRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedErrorCodesRoute: typeof AuthenticatedErrorCodesRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRouteWithChildren
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRouteWithChildren
  AuthenticatedRepairInsightsTestRoute: typeof AuthenticatedRepairInsightsTestRoute
  AuthenticatedTechTalkRoute: typeof AuthenticatedTechTalkRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommunityRoute: AuthenticatedCommunityRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnoseRoute: AuthenticatedDiagnoseRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedErrorCodesRoute: AuthenticatedErrorCodesRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRouteWithChildren,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRouteWithChildren,
  AuthenticatedRepairInsightsTestRoute: AuthenticatedRepairInsightsTestRoute,
  AuthenticatedTechTalkRoute: AuthenticatedTechTalkRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  AuthRoute: AuthRoute,
  BetaRoute: BetaRoute,
  McpRoute: McpRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
